name: mom-ime # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.9.9.7' # just for humans, typically '1.2+git' or '1.3.2'
summary: Master of Magic is a combination of an RPG and a strategy game
description: |
  Master of Magic is a combination of an RPG and a strategy game, a remake of a classic from the 90s. In Master of Magic you take up the role of one of 14 unique and diverse great wizards who compete with each other to dominate the worlds of Arcanus and Myrror.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mom-ime_icon.png
title: Masters of Magic

apps:
  mom-ime:
    command: client.sh
  mom-ime-server:
    command: server.sh
parts:
  mom-ime:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mom-ime: build/
      mom-ime.1: man/man1/

architectures:
  - build-on: amd64

